# -*- coding: utf-8 -*-
"""weather forecasting mechademy.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bmxhJEdov_hwD-NwpyGmU7rSumnXRCEX
"""

import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
from neuralprophet import NeuralProphet
import pickle

df=pd.read_csv('Weather_data(mechademy).csv')
df.head()

!pip install neuralprophet

"""**Analyzing the Patterns from the Dataset**"""

# Conds(condition)
df.conds.unique()

# Columns
df.columns

# Checking Datatype
df.info()

# Handling Date columns
df['Date']=pd.to_datetime(df['datetime_utc'])
df.head()

# Dropping datetime_utc column
del df['datetime_utc']

"""**EDA**"""

# Temprature over time
plt.plot(df['Date'], df['tempm'])
plt.show()

"""So visualization is looking nice without any break."""

# Reseting Date and temprature column
data=df[['Date', 'tempm']]
data.dropna(inplace=True)
data.columns=['ds', 'y']
data.head()

data

"""**Train Model**"""

m=NeuralProphet()
m.fit(data, freq="D", epochs=500)

"""So we got 2.26 MAE and we can say model is trained well.

**Forecast Away**
"""

future=m.make_future_dataframe(data, periods=5000)
forecast=m.predict(future)
forecast.head()

future

forecast.tail()

# Plotting the forecast
plot1=m.plot(forecast)

"""so this is the forecast through graph and its looking constantly decreasing."""

# plotting overall trend
plot2 =m.plot_components(forecast)

"""**Saving Model**"""

with open('forecast_model.pkl',"wb") as f:
  pickle.dump(m,f)

m

